### ISSUE TITLE
Solved : Add instructions for 'Add comment submission forms and rendering macros to your theme'

### ISSUE THREAD

**Issue by ABelliqueux** [push-eax/pico-comments#5]
Hi, this looks promising but I couldn't figure out how to achieve step 3 of the instructions :

> 3. Add comment submission forms and rendering macros to your theme

I realize `comments.twig` contains a sample macro but couldn't figure out how to add it to my theme's `index.twig`.

Here is what I did so far:

- Put 'PicoComments.php' in `plugins/PicoComments` : 
```
./plugins
   ├── PicoComments
          ├── comments.twig
          ├── LICENSE
          ├── PicoComments.php
          └── README.md
```
- Edited `config.yml` to include the following : 
```yml
PicoComments:
    # whether the comments plugin is enabled. comment data will not be available to Twig if this is false
    enabled: true
    # maximum character size of comments. comments larger than this will be rejected
    comment_size_limit: 1000
    # whether comments must be approved before displaying them to other users
    comment_review: false
```
- Add `comments: true` to a sample page's header.

FWIW, using Pico 2.1.4 / PHP 7.3

Can someone shed a light please ?

**EDIT**: Found the solution with the help from https://github.com/push-eax/pico-comments/issues/2#issuecomment-823636246 ;

So, step 3 instructions are : 

#### 3.a Put the `comments.twig` file in your theme's folder, e.g `pico/themes/default`;
```
pico
  └─ themes
        └─ default
              ├── [...]
              └── comments.twig
```
#### 3.b Edit `comments.twig` and replace [line 53](https://github.com/push-eax/pico-comments/blob/master/comments.twig#L53) : 

```php
    {{ print_comments(comments, false) }}
```
with
```php
    {{ _self.print_comments(comments, false) }}
```
#### 3.c In your `index.twig` file, add the following [twig instruction](https://twig.symfony.com/doc/1.x/tags/include.html) : 

```php
{{ include('comments.twig') }}
```

where you want the form to appear.
